[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.5.15", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.62.0"
lambda_http = "0.14.0"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.137"
